### PR TITLE
Don't block UI during job update

### PR DESCRIPTION
**Pull request by norberteder**
I did some minor changes on updating the jobs. This operation won't block the UI thread any more.
Furthermore a label shows that there is an update in progress (this is important after start as there are no jobs in the list/grid)

I also updated the nuget packages.

Set default job update interval to 60 seconds.

### CODE REVIEW

**Comment by DavidRogers** [comment]
Hello, @norberteder! Thanks for contributing and taking interest in this project!
So, I actually just committed some work a few days ago to update jobs in the background... Also, I'd rather not upgrade the Caliburn binaries yet since I don't know the breaking changes/consequences... 
I am open to the jobs are updating feature though, I would rather it be a little more incognito though. Instead of a text label, maybe some kind of progress spinner in the lower right corner or something like that.

**Comment by norberteder** [comment]
Hmm .. with your changes (see https://github.com/DavidRogers/kato/commit/ed0fc08f4c42ef51d2d3d57244e264b5680b0a45) the jobs aren't updated in the background.

I haven't seen any troubles with the updated binaries so far.

I've added a spinner instead of the update label (it comes from the FontWwesome.WPF NuGet module - license is ok).

**Comment by DavidRogers** [comment]
Hah! Good catch! I meant to use .WhenAll... I just made the change. You should be able to work with what I have done now. I wanted the async work to happen closer to where its needed. 
So just remove your async calls and I will get this merged in.

**Comment by norberteder** [comment]
Async calls were removed.

**Comment by DavidRogers** [comment]
Looks like you may need to rebase your work onto the latest changes and fix the conflicts.

**Comment by norberteder** [comment]
All conflicts are resolved, this should work now.

**Comment by DavidRogers** [comment]
Awesome, thanks again!

**Pull request merged**
