### PR TITLE
Normalize line endings

### PR DESCRIPTION
**Pull request by sharwell**
This commit updates the repository to properly normalize line endings for
text files in standard git fashion. The net impact is the new setting added
to **.gitattributes** is now applied uniformly, so contributors that have their
local environment configured with settings that differ from one another do
not end up checking out and committing text files with differing (or worse
mixed) line endings.

:memo: I intentionally set the author of commit e27b399 (where the new settings were applied to all files) to @DavidRogers, so as to prevent "taking ownership" of the entire codebase from the perspective of `git blame`.

:bulb: The specific commands used to normalize the line endings after creation of the **.gitattributes** file were the following. After these commands, I committed all changed files (with the exception of files removed in #17, to reduce the merge conflict to just **.gitignore**).

```
rm .git/index
git reset
```

@DavidRogers There is a minor conflict between this pull request and #17. I will gladly update either one to eliminate the merge conflict if you would like.

### CODE REVIEW

**Comment by sharwell** [comment]
@DavidRogers I have several additional pull requests ready to submit with proposed improvements, but all of them would have merge conflicts with this pull request. The strategy proposed by this pull request is helpful especially when multiple contributors are involved. Can you take a look at the approach I used as well (with setting you as the author of commit e27b399) and make a decision regarding whether to accept this or not?

Thanks! :smile:

**Comment by DavidRogers** [comment]
Would you mind updating this PR to fix the merge conficts?

**Comment by sharwell** [comment]
@DavidRogers no problem I'll update it tonight

**Comment by sharwell** [comment]
@DavidRogers Done!

**Pull request merged**
